### PR TITLE
Create a sponsorship policy

### PR DESCRIPTION
**Pull request by MarkBennett**
This is a placeholder for work on our sponsorship policy. Once we've agreed on what it is I'll update the HTML and we can merge it in.

The objectives of the sponsorship policy are:

1) Sustain the meetup
2) Reduce month-to-month administration of sponsorship
3) Share and grow the JavaScript community in Edmonton
# To Do
- [x] Create form to let sponsors sign up
- [x] Proof read
- [x] Add sponsorship announcement to May notes

### CODE REVIEW

**Comment by MarkBennett** [comment]
Hey guys! I created a pull request we can use to draft a sponsorship policy together over the next week. Feel free to edit and add the objectives and present any thoughts you have on how sponsorship might work in the comments. Once we've got some consensus we can use this PR to make a go at drafting something for the website.

@abramhindle @seanhealy @JeffMarvin

**Comment by abramhindle** [comment]
What are benefits of sponsorship?
- We mention your company.
- We promote your open positions?
- We show your logo?

Anything else?

**Comment by abramhindle** [comment]
Q: What do we expect from sponsors? 

Constraint: And as non-registered organization how do we keep it simple?

Food related issues:
- Reimbursements? Cash? Pre-order food? We probably need a few options here but some processes to address it.

**Comment by MarkBennett** [comment]
I'd definitely like to propose leaving any handling of cash out as an option at this time. This avoids needing to worry about bank accounts, incorporating as a not for profit, or holding the money in an organizers bank account in trust. I've tried to do these in the past and their a lot of work without much additional benefit. This would rule out cash and reimbursements for costs, but there are lots of other options like prepaying for services or food, or providing a credit card or person to pay for food and services.

**Comment by MarkBennett** [comment]
What kind of sponsorship opportunities exist? Here are a few I can think of..

1) Food
2) Website hosting
3) Event space
4) Volunteers to staff events
5) Conference support (if we decide to have one in the future)

Anymore?

**Comment by MarkBennett** [comment]
> What are benefits of sponsorship?
> 
> We mention your company.
> We promote your open positions?
> We show your logo?
> Anything else?

@abramhindle These look great to me.

We should be specific about how we mention sponsors. Do you just get mentioned at the meetup you sponsor? What about a logo on the homepage? Are there any specific criteria you need to meet? Any other places we should mention sponsors?

**Comment by MarkBennett** [comment]
> Q: What do we expect from sponsors?
> 
> Constraint: And as non-registered organization how do we keep it simple?
> 
> Food related issues:
> 
> Reimbursements? Cash? Pre-order food? We probably need a few options here but some processes to address it.

As I want to avoid handling cash and reimbursements, I'd say we only accept food sponsorship in the form of prepayment or payment on delivery.

**Comment by MarkBennett** [comment]
I just added some more details about how I see sponsorship working. I've broken the _food and drink_ sponsorship out from other kinds of sponsorship as the dynamics of handling it are different since it's needed at every meetup. It still feels a little complicated to me, but I like the idea of assigning sponsors twice a year.

Thoughts?

**Comment by MarkBennett** [comment]
Any feedback on this proposal? I'd like to get it in place before the next meetup.

**Comment by MarkBennett** [comment]
Hey guys, we're a little over a week away from the next meetup. I'll need to get some consensus in the next few days if I'm going to have time to set things up before the next meetup. Otherwise, it may have to be pushed back to June. Thanks.

**Comment by MarkBennett** [comment]
Hey guys, it seems like everyone else might be pretty busy right now. I'll take your silence as agreement and merge this PR on the weekend so that we've got something to announce at the meetup next week.

**Comment by MarkBennett** [comment]
I think I've integrated your feedback @JeffMarvin. Let me know if I missed anything.

> The proposed policy looks good to me, with a few notes:
> 
> “opporunity” is spelled wrong in the third paragraph , I think you want it to read “opportunity to” instead. (I am super new to Git, would I normally do an edit and commit to your current pull request?)
> 
> I think the tldr; version would benefit by adding "Supplying food and drink is the main way most groups sponsor our meetup, and we need at least one sponsor a month to make this happen.”

**Pull request merged**
