### PR TITLE
Create a Meetup Code of Conduct

### PR DESCRIPTION
**Pull request by MarkBennett**
This addresses issue #3.

### CODE REVIEW

**Comment by MarkBennett** [comment]
Can I get some feedback on this @seanhealy @abramhindle @JeffMarvin? It LGTM.

I'd like to get it in place before the next meetup.

**Comment by seanhealy** [comment]
Looks good to me! :+1:

**Comment by JeffMarvin** [comment]
Looks good. :)

**Comment by JeffMarvin** [comment]
Oops, didn't mean to close the issue!

**Comment by MarkBennett** [comment]
Thanks @seanhealy and @JeffMarvin. I'll merge this and you can make a new issue or PR if you have more feedback @abramhindle.

**Comment by abramhindle** [comment]
I felt I already agreed/argued for this on the list. I fully support this action.

**Pull request merged**
